# Generated by Django 2.2 on 2021-06-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubro',
            options={'ordering': ['-nombre'], 'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
    ]
