# Generated by Django 2.2 on 2021-06-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0002_auto_20210624_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subrubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Subrubro',
                'verbose_name_plural': 'Sububros',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='rubro',
            options={'ordering': ['nombre'], 'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(max_length=10)),
                ('concepto', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('unidades', models.CharField(max_length=10)),
                ('importe', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='economico.Rubro')),
                ('subrubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='economico.Subrubro')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['fecha'],
            },
        ),
    ]
