# Generated by Django 2.2 on 2021-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0004_auto_20210624_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umedida',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
