# Generated by Django 2.2 on 2021-06-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0005_auto_20210624_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='unidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economico.Umedida', verbose_name='Unidad de medida'),
        ),
    ]
