# Generated by Django 2.2 on 2021-06-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0008_auto_20210629_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubroGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Rubro de gasto')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(max_length=10)),
                ('concepto', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('importe', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='economico.RubroGasto')),
                ('unidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economico.Umedida', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['fecha'],
            },
        ),
    ]
