# Generated by Django 2.2 on 2021-06-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0009_rubrogasto_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubroVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Rubro de gasto')),
            ],
            options={
                'verbose_name': 'Rubro de venta',
                'verbose_name_plural': 'Rubros de ventas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='rubrogasto',
            options={'ordering': ['nombre'], 'verbose_name': 'Rubro de gasto', 'verbose_name_plural': 'Rubros de gastos'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='economico.RubroVenta'),
        ),
    ]
