# Generated by Django 2.2 on 2021-06-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0010_auto_20210630_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubrogasto',
            options={'ordering': ['nombre'], 'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
        migrations.AlterField(
            model_name='gasto',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='economico.RubroGasto'),
        ),
        migrations.AlterField(
            model_name='rubrogasto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Rubro'),
        ),
        migrations.DeleteModel(
            name='Rubro',
        ),
    ]
