# Generated by Django 2.2 on 2021-06-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0011_auto_20210630_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubrogasto',
            options={'ordering': ['nombre'], 'verbose_name': 'Rubro de gasto', 'verbose_name_plural': 'Rubros de gastos'},
        ),
        migrations.AlterField(
            model_name='gasto',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economico.RubroGasto'),
        ),
        migrations.AlterField(
            model_name='rubrogasto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Rubro de gasto'),
        ),
        migrations.AlterField(
            model_name='rubroventa',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Rubro de venta'),
        ),
    ]
