# Generated by Django 2.2 on 2021-06-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0012_auto_20210630_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='rubro',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='RubroGasto',
        ),
    ]
