# Generated by Django 2.2 on 2021-06-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0013_auto_20210630_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='rubro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='subrubro',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
