# Generated by Django 2.2 on 2021-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0014_auto_20210630_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubroGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
