# Generated by Django 2.2 on 2021-07-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0015_rubrogasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='rubro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='economico.RubroGasto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='subrubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economico.Subrubro'),
        ),
    ]
