# Generated by Django 2.2 on 2021-07-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0017_auto_20210702_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50, verbose_name='Razón Social')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIT')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50, verbose_name='Razón Social')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIT')),
                ('cbu', models.IntegerField(blank=True, null=True, verbose_name='CBU')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
