# Generated by Django 2.2 on 2021-07-03 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0018_auto_20210702_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='economico.Proveedor'),
        ),
    ]
