# Generated by Django 2.2 on 2021-07-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0019_gasto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='orden',
            field=models.IntegerField(default=0, unique=True, verbose_name='Orden'),
        ),
    ]
