# Generated by Django 2.2 on 2021-07-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0020_gasto_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='orden',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Orden'),
        ),
    ]
