# Generated by Django 2.2 on 2021-07-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0021_auto_20210720_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='orden',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
    ]
