# Generated by Django 2.2 on 2021-07-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0022_auto_20210720_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
