# Generated by Django 2.2 on 2021-07-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0024_auto_20210720_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='orden',
        ),
    ]
