# Generated by Django 2.2 on 2021-07-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0025_remove_gasto_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
