# Generated by Django 2.2 on 2021-07-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0026_gasto_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='orden',
        ),
    ]
