# Generated by Django 2.2 on 2021-07-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economico', '0027_remove_gasto_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasto',
            name='vto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
    ]
