# Generated by Django 2.2 on 2021-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdLeche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('venta', models.IntegerField()),
                ('consumo', models.IntegerField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Temperatura entregada')),
            ],
            options={
                'verbose_name': 'Produccion de Leche',
                'verbose_name_plural': 'Produccion de Leche',
                'ordering': ('-fecha',),
            },
        ),
    ]
