# Generated by Django 2.2 on 2021-06-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_auto_20210617_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatAlimento',
        ),
        migrations.RemoveField(
            model_name='existenciaanimal',
            name='cat',
        ),
        migrations.AlterField(
            model_name='prodleche',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Temperatura entregada'),
        ),
        migrations.DeleteModel(
            name='CatAnimal',
        ),
        migrations.DeleteModel(
            name='ExistenciaAnimal',
        ),
    ]
