# Generated by Django 2.2 on 2021-06-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_auto_20210617_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría animal',
                'verbose_name_plural': 'Categoría animales',
                'ordering': ('cat',),
            },
        ),
    ]
