# Generated by Django 2.2 on 2021-06-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_catalimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciaAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('grupo', models.CharField(choices=[(1, 'Rodeo/Leche'), (2, 'Carne')], max_length=30)),
                ('cantidad', models.IntegerField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.CatAnimal')),
            ],
            options={
                'verbose_name': 'Existencia animal',
                'verbose_name_plural': 'Existencias animales',
                'ordering': ('cat',),
            },
        ),
    ]
