# Generated by Django 2.2 on 2021-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_existenciaanimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalimento',
            options={'ordering': ('alimento',), 'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
        migrations.RemoveField(
            model_name='catalimento',
            name='cat',
        ),
        migrations.AddField(
            model_name='catalimento',
            name='alimento',
            field=models.CharField(default=1, max_length=100, verbose_name='Alimento'),
            preserve_default=False,
        ),
    ]
