# Generated by Django 2.2 on 2021-06-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_auto_20210617_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatAlimento',
            new_name='Alimento',
        ),
    ]
