# Generated by Django 2.2 on 2021-06-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_auto_20210618_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodleche',
            name='vo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
