# Generated by Django 2.2 on 2021-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_prodleche_vo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='existenciaanimal',
            options={'ordering': ('cat',), 'verbose_name': 'Existencia animal', 'verbose_name_plural': 'Existencia de animales'},
        ),
        migrations.AlterField(
            model_name='existenciaanimal',
            name='grupo',
            field=models.CharField(choices=[(1, 'Rodeo de Tambo'), (2, 'Rodeo de Carne')], max_length=30, verbose_name='Rodeo'),
        ),
    ]
