# Generated by Django 2.2 on 2021-06-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_auto_20210624_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciaanimal',
            name='grupo',
            field=models.CharField(choices=[('Tambo', 'Rodeo de Tambo'), ('Carne', 'Rodeo de Carne')], max_length=5, verbose_name='Rodeo'),
        ),
    ]
