# Generated by Django 2.2 on 2021-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_auto_20210624_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciaTambo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vo', models.IntegerField(verbose_name='VO')),
                ('vs', models.IntegerField(verbose_name='VS')),
                ('vaqpp', models.IntegerField(verbose_name='Vaq. PP')),
                ('vaqcserv', models.IntegerField(verbose_name='Vaq/Servicio')),
            ],
            options={
                'verbose_name': 'Existencia Tambo',
                'verbose_name_plural': 'Existencias de Tambo',
                'ordering': ('-fecha',),
            },
        ),
        migrations.DeleteModel(
            name='ExistenciaAnimal',
        ),
    ]
