# Generated by Django 2.2 on 2021-06-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0013_auto_20210625_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='existenciatambo',
            name='to',
            field=models.IntegerField(default=0, verbose_name='Toros'),
        ),
    ]
