# Generated by Django 2.2 on 2021-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_existenciatambo_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatAnimal',
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Toros'),
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='vaqcserv',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vaq/Servicio'),
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='vaqpp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vaq. PP'),
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='vo',
            field=models.IntegerField(blank=True, null=True, verbose_name='VO'),
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='vs',
            field=models.IntegerField(blank=True, null=True, verbose_name='VS'),
        ),
    ]
