# Generated by Django 2.2 on 2021-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0015_auto_20210625_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciaRecria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('terneros', models.IntegerField(blank=True, null=True, verbose_name='Terneros')),
                ('recria', models.IntegerField(blank=True, null=True, verbose_name='Recría')),
                ('vaq', models.IntegerField(blank=True, null=True, verbose_name='Vaquillonas')),
                ('nov', models.IntegerField(blank=True, null=True, verbose_name='Novillos')),
            ],
            options={
                'verbose_name': 'Existencia de Bovinos derivados del tambo',
                'verbose_name_plural': 'Existencias de Bovinos derivados del tambo',
                'ordering': ('-fecha',),
            },
        ),
    ]
