# Generated by Django 2.2 on 2021-06-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0016_existenciarecria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciarecria',
            name='nov',
            field=models.IntegerField(default=0, verbose_name='Novillos'),
        ),
        migrations.AlterField(
            model_name='existenciarecria',
            name='recria',
            field=models.IntegerField(default=0, verbose_name='Recría'),
        ),
        migrations.AlterField(
            model_name='existenciarecria',
            name='terneros',
            field=models.IntegerField(default=0, verbose_name='Terneros'),
        ),
        migrations.AlterField(
            model_name='existenciarecria',
            name='vaq',
            field=models.IntegerField(default=0, verbose_name='Vaquillonas'),
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='to',
            field=models.IntegerField(default=0, verbose_name='Toros'),
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='vaqcserv',
            field=models.IntegerField(default=0, verbose_name='Vaq/Servicio'),
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='vaqpp',
            field=models.IntegerField(default=0, verbose_name='Vaq. PP'),
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='vo',
            field=models.IntegerField(default=0, verbose_name='VO'),
        ),
        migrations.AlterField(
            model_name='existenciatambo',
            name='vs',
            field=models.IntegerField(default=0, verbose_name='VS'),
        ),
    ]
