# Generated by Django 2.2 on 2021-06-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0017_auto_20210625_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existenciatambo',
            name='vaqcserv',
        ),
        migrations.AddField(
            model_name='existenciarecria',
            name='vaqcserv',
            field=models.IntegerField(default=0, verbose_name='Vaq/Servicio'),
        ),
    ]
