# Generated by Django 2.2 on 2021-07-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0019_auto_20210701_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciatambo',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
