# Generated by Django 2.2 on 2021-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0020_auto_20210704_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciatambo',
            name='fecha',
            field=models.DateField(),
        ),
    ]
