# Generated by Django 2.2 on 2021-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0021_auto_20210706_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciatambo',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
