# Generated by Django 2.2 on 2021-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0022_auto_20210706_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciatambo',
            name='fecha',
            field=models.DateField(),
        ),
    ]
